DIALECT='mysql'
DRIVER='pymysql'
USERNAME="root"
PASSWORD="202106"
HOST="127.0.0.1"
PORT="3306"
DATABASE="headline"
SQLALCHEMY_DATABASE_URI="{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT,DRIVER,USERNAME,PASSWORD,HOST,PORT,DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS=False


MAIL_PORT='465'
MAIL_USE_SSL=True
MAIL_SERVER="smtp.qq.com"
MAIL_USERNAME="943382615@qq.com"
MAIL_PASSWORD="vojqhaqghrrrbfei"
MAIL_DEFAULT_SENDER=("理论头条","943382615@qq.com")

UPLOAD_PATH="./static/img/"
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])
MAX_CONTENT_LENGTH=1024*1024

SECRET_KEY="VICTOR"
